### ISSUE TITLE
Unexpected Token 'import'

### ISSUE THREAD

**Issue by ghost** [vitalets/react-native-extended-stylesheet#10]
Getting this error when running my project after adding this dependency. We're running babel (stage-2). Any idea why this is happening?

**Comment by vitalets** [comment]
hi @dustinsavery 
1. do you use also `preset-es2015` ?
2. do you use `import/export` in your own code?

**Comment by fab1an** [comment]
I have the same problem. It has to do that babel doesn't transpile dependencies in node_modules. Those should be transpiled into a `lib` folder or similar before publishing!

**Comment by vitalets** [comment]
thanks @fab1an! Will fix it.

**Comment by fab1an** [comment]
Check the referenced bug first, it's not easy to depend on react-native atm.

**Comment by vitalets** [comment]
All example are wiorking on actual version of RN.
Feel free to reopen if bug still exists.
