### ISSUE TITLE
Estyle sheet in Type script

### ISSUE THREAD

**Issue by Amit2530** [vitalets/react-native-extended-stylesheet#104]
When we try to use the EstyleSheet in type script file of React native project then the styles are not working as expected ?

**Comment by vitalets** [comment]
Please provide more details: error messages, screenshots, etc.

**Comment by Amit2530** [comment]
When i use the normal style then UI is working properly, can you refer below screen shot --
![stylesheet](https://user-images.githubusercontent.com/41721563/52173827-ef096180-27a4-11e9-97fb-7c66e53669e8.jpeg) 

And when i try to use the style through the Estyle sheet then it is not working as we are expectin, please refer below screen shot --
![estylesheet](https://user-images.githubusercontent.com/41721563/52173826-ef096180-27a4-11e9-8041-3f3cb1b4fa3e.jpeg)

**Comment by vitalets** [comment]
Have you called `EStyleSheet.build()` in the code?

**Comment by Amit2530** [comment]
Yes

**Comment by Amit2530** [comment]
Yes, we are trying to use the type script in our react native project.
