### ISSUE TITLE
Need to combine Stylesheet in order to create global styles

### ISSUE THREAD

**Issue by gungdeaditya** [vitalets/react-native-extended-stylesheet#107]
Is it possible if we use spread operator to combine stylesheet, because I tried but had no succeed

**Comment by vitalets** [comment]
Yes, it is possible. Could you show the code how did you try?

**Comment by edwang2007** [comment]
I am having the same issue.

`import EStyleSheet from 'react-native-extended-stylesheet';
import globalStyles from '../GlobalStyles';

const styles = EStyleSheet.create({
    ...globalStyles,
    container: {
        flex: 1,
    },
});`

`import EStyleSheet from 'react-native-extended-stylesheet';

const globalStyles = EStyleSheet.create({
    headerContainer: {
        flex: 1,
        alignSelf: 'center',
    },
    headerText: {
        fontSize: '80rem',
    }
});

export default globalStyles;`

**Comment by vitalets** [comment]
hi @edwang2007 !

Is it possible for you app to define global styles as raw object?
For example:

**GlobalStyles.js**
```js
export default {
    headerContainer: {
        flex: 1,
        alignSelf: 'center',
    },
    headerText: {
        fontSize: '80rem',
    }
};
```

**Component.js**
```js
import EStyleSheet from 'react-native-extended-stylesheet';
import globalStyles from '../GlobalStyles';

const styles = EStyleSheet.create({
    ...globalStyles,
    container: {
        flex: 1,
    },
});
```
