### ISSUE TITLE
Shall I memoize() the sheet if the only vars changing are media-queries related. How to do it?

### ISSUE THREAD

**Issue by amarchen** [vitalets/react-native-extended-stylesheet#11]
I have zero global variables for stylesheets, yet quite some changes depending on the device orientation and thus on media queries.

Therefore I am calling `create()` on every rotation. How should I `memoize()` stylesheets in such a situation not to recalculate same sheet many times or is it possible at all?

**Comment by vitalets** [comment]
After implementing orientation support in #9 portrait/landscape styles will be cached automatically.
Memoize is intended for cases when you create components dynamically with set of styles.
