### ISSUE TITLE
Attribute "rgba(255,255,255,.7)" missed quot(")!! 

### ISSUE THREAD

**Issue by pacientk** [vitalets/react-native-extended-stylesheet#115]
How to rid from React Native Debugger warning:

![image](https://user-images.githubusercontent.com/19683664/64106379-bce2d100-cd80-11e9-9efe-d9f4bbc836d5.png)

[xmldom warning] attribute "rgba(255,255,255,.7)" missed quot(")!! YellowBox.js:67

Of course I tried to change quotes to " and ' and ` - no result

**Comment by pacientk** [comment]
Yes, it still relevant. 
I didnt found solution for it. Can you help me with it?

**Comment by vitalets** [comment]
@pacientk Could you show the code?

**Comment by pacientk** [comment]
what the code specific?

This is the warnings: 
![image](https://user-images.githubusercontent.com/19683664/70250981-6d4ce080-1787-11ea-8fcc-6edf9252359b.png)

This is example of global styles of project:
![image](https://user-images.githubusercontent.com/19683664/70251213-c3218880-1787-11ea-96ca-122bb24a0c9f.png)

**Comment by pacientk** [comment]
Is there any solution?

**Comment by leobetosouza** [comment]
Probably the solution is use `$black_90: "'rbga(0, 0, 0, .9)'"` or `$black_90: '"rbga(0, 0, 0, .9)"'` on every statement. Sadly I am without time to try this.

**Comment by pacientk** [comment]
> Probably the solution is use `$black_90: "'rbga(0, 0, 0, .9)'"` or `$black_90: '"rbga(0, 0, 0, .9)"'` on every statement. Sadly I am without time to try this.

Thx. I will try...
