### ISSUE TITLE
Question: Have you also minded the DP problem?

### ISSUE THREAD

**Issue by juriuschakow** [vitalets/react-native-extended-stylesheet#117]
Hi! Can I use the REM feature provided in your library without a problem, or do I have to use this library here because of the DP problem?

https://github.com/marudy/react-native-responsive-screen
https://medium.com/building-with-react-native/how-to-develop-responsive-uis-with-react-native-1x03-a448097c9503

Sorry for the dumb question I am a beginner.

Thank you very much!

**Comment by Subway19** [comment]
I use both libraries. No issues yet.
