### ISSUE TITLE
ReferenceError: Can't find veriable: style

### ISSUE THREAD

**Issue by detroit007** [vitalets/react-native-extended-stylesheet#120]
#### Steps to Reproduce
it's totally not able to find style variable I deleted all of them just until there is only one on the page but still, that one style variable showing error.
#### Actual Behavior

ReferenceError: Can't find veriable: style
This error is located at:
in App(at renderApplication.js:40)
in RCTView (at AppContainer.js:101)
in RCTView (at AppContainer.js:119)
in AppContainer(at renderApplication.js:39)

#### Show the code
import React from 'react';
import {
  StyleSheet,
  View,
  Text,
  Button,
  TouchableOpacity,
} from 'react-native';

import DefaultInputText from './components/DefaultInputText';

const App: () => React$Node = () => {
  return (
      <View style={styles.contain}>
           <Text style={styles.headText}>React Form</Text>
          
              <TouchableOpacity  style={styles.btn}>
                      <Text style={styles.btnText}>SUBMIT</Text>
           </TouchableOpacity>
        
        </View>
);
};
const styles = StyleSheet.create({

      contain:  { padding: 20 },

      headText: {
           textAlign: 'center',
           fontSize: 40,
           marginVertical: 20,
           fontWeight: 'bold',
           color: '#0059F2'
      },
      btn: {
           marginTop: 20,
           height: 50,
           borderRadius: 4,
           borderWidth: 1,
           borderColor: 'transparent',
           backgroundColor: '#2196F3'
      },
      btnText: {
           paddingVertical: 12,
           color: 'white',
           fontSize: 18,
           fontWeight: 'bold',
           textAlign: 'center'
      }

    });
export default App;

#### Environment
I am using Ubuntu with Android Studio, how do I style my page now. help!

**Comment by progsmile** [comment]
@detroit007 try to wipe data from emulator and that start again
Seems like it's not library error
