### ISSUE TITLE
Is this repo working with RN 0.61.5?

### ISSUE THREAD

**Issue by danieldelouya** [vitalets/react-native-extended-stylesheet#128]
#### Steps to Reproduce
Installed the repo. Imported it in a screen. It doesn't render anything from the StyleSheet when it's `EStyleSheet.create` instead of the default `StyleSheet.create`

#### Try in Expo
Not using expo. 

#### Expected Behavior
Expected it to just work (recognize the styles in the stylesheet)

#### Actual Behavior
Styles not recognized.

#### Show the code
`const styles = EStyleSheet.create({
  safeAreaView: {
    backgroundColor: 'white',
    width: 200
  }
})`

#### Environment
System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 157.15 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.1.0 - ~/.nvm/versions/node/v12.1.0/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.1.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 26.0.2, 27.0.3, 28.0.2, 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-R | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by AgustinGMartinez** [comment]
Same problem.

**Comment by marcpassarelli** [comment]
@danieldelouya I was facing the same issue but then I realized that I was forgetting to call EStyleSheet.build() in app entry point. Not sure if that would be your case.

[see here in the 2.](https://github.com/vitalets/react-native-extended-stylesheet#usage)

**Comment by FrederickEngelhardt** [comment]
I was on 0.61.5 and had no issues. Also no issue on 0.62.2. Betting it's an entrypoint issue.
