### ISSUE TITLE
Math operations not performed on transform prop

### ISSUE THREAD

**Issue by artsra** [vitalets/react-native-extended-stylesheet#130]
#### Steps to Reproduce
Using   "version": "0.12.0"

See snack below. Removing the two indicated lines in my_component fixes the vertical transform
I think this is a problem here:

```
style.calcProps() {
    this.extractedProps = utils.excludeKeys(this.processedSource, this.extractedVars);
    this.calculatedProps = calcPlainObject(this.extractedProps, this.varsArr);
  }

function calcPlainObject(obj, varsArr) {
  return Object.keys(obj).reduce((res, prop) => {
    res[prop] = calcStyleValue(prop, obj[prop], varsArr);
    return res;
  }, {});
}

function calcStyleValue(prop, value, varsArr) {
  const isNestedValue = (value && typeof value === 'object' && !Array.isArray(value));
  return  isNestedValue
    ? calcPlainObject(value, varsArr)
    : new Value(value, prop, varsArr).calc();
}

Value.calc() {
    if (typeof this.value === 'function') {
      this.value = this.value();
    }

    if (typeof this.value === 'string') {
      this.calcString();
    } else {
      this.proxyValue();
    }

    if (this.isFinal()) {
      this.applyScale();
    }

    return this.outValue;
  }
```
At some point the following prop is processed by calcStyleValue:

```
    transform: [
      { rotate: '270deg' },
      { translateX: '0 - $VERT_LABEL_TEXT_OFFSET' },
      { translateY: '$VERT_LABEL_TEXT_OFFSET' },
    ],
```
`calcStyleValue` finds that a new Value().calc() must be performed, but the calc() just proxies the value because it's an array. The new (proxied) value is returned but math operations are not done.

I'm not sure how to fix this, what would be the best solution?

#### Try in Expo
https://snack.expo.io/@artsr/extended-stylesheet-simple

#### Expected Behavior
The Math operations were processed correctly

#### Actual Behavior
They are not processed, and result in errors. See attached image. Ignored on web platform but makes transform stop working.

#### Show the code
See snack

#### Environment

command not found: react-native (this is an expo project)

<img width="390" alt="Schermafbeelding 2020-04-14 om 22 08 15" src="https://user-images.githubusercontent.com/55588494/79269516-e0d0ce00-7e9c-11ea-83d1-3b6f7a1a7d81.png">

**Comment by ningacoding** [comment]
This issue persists.
