### ISSUE TITLE
The package returns an empty object

### ISSUE THREAD

**Issue by nateblog** [vitalets/react-native-extended-stylesheet#134]
#### Steps to Reproduce
1. install the package
2. import the package `import EStyleSheet from 'react-native-extended-stylesheet';`
3. then use it

#### Expected Behavior
The package **EStyleSheet** should return an object that contains all the style properties.

#### Actual Behavior
It returned an empty object

#### Show the code
```
import {Dimensions} from 'react-native';
import EStyleSheet from 'react-native-extended-stylesheet';
import {theme} from '../appConfig.json';

const {width} = Dimensions.get('window');
const styles = EStyleSheet.build({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.primary,
  },
  landing_sections: {
    flex: 1,
    width,
    justifyContent: 'center',
    alignItems: 'center',
  },

  appTitleWrapper: {
    backgroundColor: 'red',
    width: '90%',
    height: '25%',
    aspectRatio: 3.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  appTitle: {
    fontSize: 60,
    fontFamily: 'GoodVibrationsScript',
    textAlign: 'center',
    color: '#fff',
    paddingRight: 10,
  },
});
console.log(styles) <---- EMPTY OBJECT
export default styles;
```

#### Environment
"react-native": "0.61.5",
"react-native-extended-stylesheet": "^0.12.0",

**Comment by ipakhomov** [comment]
@nateblog I noticed, that you use call `EStyleSheet.build({ ...your styles here })` to create styles - this function does not return anything. Please try to create your styles using `EStyleSheet.create({ ...styles here })` instead.

Also, maybe [this comment](https://github.com/vitalets/react-native-extended-stylesheet/issues/82#issuecomment-380143248) may help you?
