### ISSUE TITLE
'unsubscribe' not in TypeScript Type

### ISSUE THREAD

**Issue by RobertFischer** [vitalets/react-native-extended-stylesheet#135]
#### Steps to Reproduce
  1. Look in `api.js` and see that there is, indeed, an `unsubscribe` method implemented there.
  2. Look in `index.d.ts` and see that there is *not* an `unsubscribe` method documented there.

#### Expected Behavior

I would have expected `unsubscribe` to be documented in the type. 

#### Actual Behavior

Typescript complains that `unsubscribe` is not a method in the type.

**Comment by neXorianus** [comment]
same as #133 
looks like ts support is badly implemented.
