### ISSUE TITLE
media-queries.js file throws error when ran on Android

### ISSUE THREAD

**Issue by PimDeWitte** [vitalets/react-native-extended-stylesheet#14]
So the library works great on iOS, but when I try to run the same library on Android, I receive the following error on startup. 

<img width="348" alt="screen shot 2016-06-07 at 4 58 15 pm" src="https://cloud.githubusercontent.com/assets/8763534/15878599/1a8af444-2cd1-11e6-93d4-e8a33b93aee8.png">

It's on this line: `const res = Object.keys(obj).reduce((res, key) => {`

I've read up on the other issues and it looks like Android is not setting these properties correctly. Can you please advise?

My code:

<img width="796" alt="screen shot 2016-06-07 at 5 01 49 pm" src="https://cloud.githubusercontent.com/assets/8763534/15878655/970cbe3a-2cd1-11e6-90e7-dcf04dd44a43.png">

**Comment by PimDeWitte** [comment]
When removing the .build() function, it works fine, except obviously the EStyleSheets don't work, but the rest of the app functions fine. Should I call it at some other location in the app?

**Comment by PimDeWitte** [comment]
I fixed it by replacing the process function in media-queries.js
`
 */
function process(obj) {


  const mqKeys = [];

  if(obj === undefined || obj.length <= 0) {
    return null;
  }
  // copy non-media-query stuff
  const res = Object.keys(obj).reduce((res, key) => {
    if (!isMediaQuery(key)) {
      res[key] = obj[key];
    } else {
      mqKeys.push(key);
    }
    return res;
  }, {});

  // apply media query stuff
  if (mqKeys.length) {
    const matchObject = getMatchObject();
    mqKeys.forEach(key => {
      const mqStr = key.replace(PREFIX, '');
      const isMatch = mediaQuery.match(mqStr, matchObject);
      if (isMatch) {
        merge(res, obj[key]);
      }
    });
  }

  return res;
}`

**Comment by PimDeWitte** [comment]
Fixed in #15

**Comment by PimDeWitte** [comment]
Reopned because issue is not fixed. I'm not sure why - but the error has returned even with the null checks. 
<img width="507" alt="screen shot 2016-06-08 at 10 22 36 am" src="https://cloud.githubusercontent.com/assets/8763534/15903742/0ae68fe8-2d63-11e6-9081-6037228408aa.png">

**Comment by vitalets** [comment]
hi @PimDeWitte 

could you show the object that you pass to  `EStyleSheet.create()` ?
