### ISSUE TITLE
SyntaxError with jest, babel, and react-native-web

### ISSUE THREAD

**Issue by kumar303** [vitalets/react-native-extended-stylesheet#143]
#### Steps to Reproduce

Is there something I'm missing to set up Jest? I get this when Jest runs my test:

```
  ● Test suite failed to run

    <project_path>/node_modules/react-native-extended-stylesheet/src/index.js:5
    import Api from './api';
           ^^^

    SyntaxError: Unexpected identifier
```

The stack trace points to the first place my app under test tries to import `react-native-extended-stylesheet`.

I tried adding `__mocks__` like [the jest-testing example](https://github.com/vitalets/react-native-extended-stylesheet/tree/master/examples/jest-testing) but I get the same `SyntaxError` when it tries to load the mock (in the `require` statement).

Do I need a special babel transform?

#### Show the code

My `babel.config.js`:

```js
module.exports = {
  plugins: [["react-native-web", { commonjs: true }]],
  presets: [
    ["@babel/preset-env", { targets: { node: "current" } }],
    "@babel/preset-react",
    "@babel/preset-typescript",
  ],
};
```

My `jest.config.js`:

```js
module.exports = {
  setupFiles: ["<rootDir>src/__tests__/setupJsDom.js"],
  setupFilesAfterEnv: ["<rootDir>src/__tests__/setupTests.tsx"],
  testEnvironment: "node",
  testPathIgnorePatterns: [
    "/node_modules/",
    "<rootDir>/build/",
    "<rootDir>/src/__tests__/helpers.*",
    "<rootDir>/src/__tests__/setup.*",
  ],
  // This needs to match the url in __tests__/setupJsDom.js
  testURL: "http://localhost",
};
```

#### Environment

N/A because I'm using `react-native-web`?

I am using `react-native-extended-stylesheet@0.12.0`, `react-native-web@0.13.3`, `@babel/core@7.10.3`, and `jest@26.0.1`

**Comment by Mister-CK** [comment]
Yes, this is still relevant, we are running into this issue right now.
