### ISSUE TITLE
Ambiguity about aspect-ratio media query - screen vs window area

### ISSUE THREAD

**Issue by ragecryx** [vitalets/react-native-extended-stylesheet#146]
It should be clear as to which aspect ratio the library checks against. And if both can't be supported then the one supported probably needs to be the Screen area not the Window area as it currently is.

#### Steps to Reproduce
1. Have a project using the library
2. Make sure it has a media query like `@media (aspect-ratio: 9/16)`
3. Run the project in an android device with 9/16 aspect ratio but with virtualized bottom 3 buttons
4. The media query is not matched because it's based on window width and height

In my case with a Galaxy Nexus AVD at 720 x 1280 resolution the rule matches `@media (aspect-ratio: 45/74)` but **not**  `@media (aspect-ratio: 9/16)` as I expected.

**Comment by dimgrav** [comment]
Still open

**Comment by ragecryx** [comment]
After some thought it's good that the library means the available space because you can have split-screen apps for example and you may want to adapt the UI properly. So adding something like `screen-aspect-ratio` should be the best solution.

**Comment by vitalets** [comment]
> In my case with a Galaxy Nexus AVD at 720 x 1280 resolution the rule matches `@media (aspect-ratio: 45/74)` but **not** `@media (aspect-ratio: 9/16)` as I expected.

Ca not it be solved with `min-aspect-ratio` and `max-aspect-ratio`? Like this:
```js
'@media (min-aspect-ratio: 9/16) and (max-aspect-ratio: 45/74)': {
  column: {
    width: '90%',
  }
}
```

Sorry for late response.
