### ISSUE TITLE
Re-build stylesheets on hot reload

### ISSUE THREAD

**Issue by Kerumen** [vitalets/react-native-extended-stylesheet#16]
Is it possible?

I tried the following but it's not working.

``` javascript
if (module.hot) {
  module.hot.accept(() => {
    EStyleSheet.build();
  });
}
```

**Comment by vitalets** [comment]
hi, 
it should be possible after https://github.com/vitalets/react-native-extended-stylesheet/issues/7
What error message you are getting?

**Comment by Kerumen** [comment]
I don't have any error message. It's just not working silently.

**Comment by vitalets** [comment]
I think styles are re-calculated, but components are not re-rendered automatically (because `EStyleSheet.build();` does not force re-render, it's just re-calculates styles).
Could you check it somehow? Maybe call `forceUpdate()` on some component after `EStyleSheet.build()` caused by hot reload?

**Comment by Kerumen** [comment]
Yup, you were right. Any ideas about how can I force the rerender ? 
I can't put a `forceUpdate` in each component..

**Comment by vitalets** [comment]
Agree. It's not the solution to manually update components.
Currently i'm working on re-render components on orientation change #9 and in fact it is the same task.
I think we will wrap top components into mixin that will keep them update on an style changes (no matter it was hot reload or orientation change)
So waiting for #9 here..

**Comment by Kerumen** [comment]
Okey I will #9, thanks :)

**Comment by gastonmorixe** [comment]
Any updates on this? I have  styles.js file and it is not updating on hot reload.

**Comment by vitalets** [comment]
@gastonmorixe Could you provide a simple snippet demonstrating it?

**Comment by alvinwoon** [comment]
+1. HMR is broken for some reason. Using it via Expo tho.

**Comment by vitalets** [comment]
I'll keep this open to not forget about hot reload.

**Comment by vitalets** [comment]
Released support of HMR in 0.8.0. Also added a [docs section](https://github.com/vitalets/react-native-extended-stylesheet#hot-module-reload).
Feel free to reopen in case of any issues.

**Comment by corysimmons** [comment]
@vitalets Non-support for HMR is still mentioned in README under caveats. https://github.com/vitalets/react-native-extended-stylesheet#caveats

If you're happy with 0.8+ implementation of it, can we remove that warning from README?

**Comment by gastonmorixe** [comment]
is HMR working when styles are in a external file? It's not working for me (in React Native 0.53)

**Comment by vitalets** [comment]
@gastonmorixe Could you show some demonstrating code if possible?

**Comment by joelgetaction** [comment]
NOTE: This code:
```
module.hot.accept(() => {
	      EStyleSheet.clearCache();
	      EStyleSheet.build(); // force style re-calculation
	    });
```
will crash release builds instantly on launch that are uploaded and distributed via TestFlight, so be sure to exclude it from your release builds.

**Comment by vitalets** [comment]
@joelgetaction Could you show the crash trace?
