### ISSUE TITLE
Why round?

### ISSUE THREAD

**Issue by Kerumen** [vitalets/react-native-extended-stylesheet#17]
I was wondering why [round all calculated variables](https://github.com/vitalets/react-native-extended-stylesheet/blob/master/src/value.js#L48)?

I blocked on this because I have a `borderWidth` variable of `0.5` but it gets rounded to `1` and it's frustrating..

React Native [already round the style](https://facebook.github.io/react-native/docs/pixelratio.html#pixel-grid-snapping) for pixel snapping so it seems unneeded.

**Comment by vitalets** [comment]
hi @Kerumen 

thanks for the info! I agree rounding is not needed. Could you make a pr?

**Comment by pampang** [comment]
Without rounding, how can I fixed lineHeight which needs its value to be an integer?

**Comment by vitalets** [comment]
@pampang does not RN do it itself?

**Comment by pampang** [comment]
@vitalets RN just alert an error, and that's all.
I've make it right by using my code like below:
`lineHeight: Math.round(EStyleSheet.value('1.8rem'))`

**Comment by vitalets** [comment]
Ok, got it.
So it seems we should revert this change and allow RN to round when needed.

@Kerumen did you face such problems?

**Comment by Kerumen** [comment]
@vitalets No, never.

I don't think we should revert this change because at the moment we can manually round as @pampang did. But if the library round, there is no way for the user to prevent this. So my `borderWidth` variable will be `1` instead of `0.5` and I can't manually change this.

**Comment by vitalets** [comment]
@pampang could you screenshot an alert?

**Comment by pampang** [comment]
@vitalets
This issue is discussed in https://github.com/facebook/react-native/issues/7877 for a while.
I am using RN 0.37.0. Maybe it is a bug that fixed by RN 0.39.1.

**Comment by Kerumen** [comment]
Sorry I tested only on iOS. This seems to happen on Android.

**Comment by egormerkushev** [comment]
So, what is proper way to round line heights with EStyleSheet for Android?

**Comment by vitalets** [comment]
hi @egormerkushev !
RN rounds pixel values automatically. 
Do you have any warnings if you don't round manually?
```js
  tileText: {
    ...
    lineHeight: '$baseLineHeight*$h5FontSize',
  }
```

**Comment by egormerkushev** [comment]
@vitalets I use RN 0.42 and using not whole values for line heights causes a crash on Android 6.0 for example.

**Comment by vitalets** [comment]
Yes, by https://github.com/facebook/react-native/issues/7877#issuecomment-223323649 `lineHeight` property in RN must be integer. And throws error if not. 
I also think it's [inconsistent with other styles](https://react-native.canny.io/feature-requests/p/error-while-updating-property-lineheight-in-shadow-node-of-type-rcttext) (that just round values).

So especially for `lineHeight` we should round manually as you done.

**Comment by egormerkushev** [comment]
@vitalets yep. I uprooted for this feature request yesterday. If my solution is not bad - may be it will be useful for other developers. ✌🏻
