### ISSUE TITLE
Universal support?

### ISSUE THREAD

**Issue by ericmuyser** [vitalets/react-native-extended-stylesheet#2]
Hey vitalets!

Awesome library man. It would be super cool if this could compile on web too. Do you think that would be much effort? If not, I might look into trying to do that. I'm looking for something that works in native and progressively enhances if it can (eg. inside browser).

Cheers

**Comment by vitalets** [comment]
hi @ericmuyser 

interesting point, did not think about it. Could you give more explanation which tasks on web it should solve?
In web for managing styles there are css preprocessors (saas, less, stylus).. aren't they do the job?

**Comment by ericmuyser** [comment]
Hi @vitalets 

If you build your components on native and you want it to run on web too, how would you do that if you are using `react-native-extended-stylesheet`? Duplicate the code?

**Comment by vitalets** [comment]
Hmm.. what about components that uses original RN StyleSheets, how do they translated into css for web? 
Because extended stylesheets are calculated to usual stylesheets at the end..

**Comment by ericmuyser** [comment]
Personally I would just continue to do it the same as native, for consistency: inline styles. If it works on native, why re-write it on web?

**Comment by vitalets** [comment]
Sorry, maybe I'm missing something.. could you show the code or repo with component that is re-used in both native and web platforms?

**Comment by tuckerconnelly** [comment]
Hey @ericmuyser , I have a similar library that supports web and native over here :) https://github.com/tuckerconnelly/uranium
