### ISSUE TITLE
auto?

### ISSUE THREAD

**Issue by steviesama** [vitalets/react-native-extended-stylesheet#20]
I was led to this project because someone said you could do something to the effect of `width='100%' height='auto'`.

I can't get it to work. Does this functionality exist?

**Comment by vitalets** [comment]
Hi @steviesama 

could you show the code that does not work as expected?

**Comment by jonlay** [comment]
Same issue here, trying to get myself scaleable images. Here's my full component, just for reference:

    import React, { Component } from 'react';
    import { Image } from 'react-native';
    import EStyleSheet from 'react-native-extended-stylesheet';

    export default class ImageDefault extends Component {
      setNativeProps(nativeProps) {
        this._root.setNativeProps(nativeProps);
      }

      render() {
        return (
          <Image {...this.props} style={[styles.image, this.props.style]} />
        )
      }
    }

    const styles = EStyleSheet.create({
      image: {,
        height: 'auto',
        width: '50%',
      }
    })

Error is:

Invalid prop `height` of type `string` supplied to `StyleSheet Image`, expected `number`

**Comment by tiempham** [comment]
@jonlay fix it image: {,
