### ISSUE TITLE
first-child not working?

### ISSUE THREAD

**Issue by JClackett** [vitalets/react-native-extended-stylesheet#24]
Not sure if i'm making a mistake but, :first-child pseudo class doesn't seem to be working for me, last-child, even, and odd all seem to work fine?

It still takes the 'left: 50' for first child

In my styles:

```
event_guest: {
    position: "absolute",
    height: 40,
    borderColor: "white",
    width: 40,
    marginTop: 10,
    left: 30,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "#FFF"
},
'event_guest:nth-child-even': {
    left:50,
},
'event_guest:first-child': {
    left:10,
},
```

**Comment by JClackett** [comment]
Or if there is a way to select only the second element, that would be useful, i didnt really understand if that was possible from the docs?

**Comment by vitalets** [comment]
Just re-checked `:first-child` in example, it seems to work.
Please have a look on this: https://github.com/vitalets/react-native-extended-stylesheet/tree/master/examples/readme

**Comment by BlueApple865729** [comment]
I wanna see the real code. How can I use pseudo class in React Native.
