### ISSUE TITLE
media queries for global variables

### ISSUE THREAD

**Issue by karpoff** [vitalets/react-native-extended-stylesheet#25]
Hi

Is it possible to use medai queries while setting global variables?
I want to set different values depending on IOS/android while EStyleSheet.build but it doesn't work

PS I know that I can do it with native Platform, but probably I'll use other media queries

and thanks for great extension

**Comment by vitalets** [comment]
hi @karpoff 

you are right, currently it's not possible but suggestion makes sense to me.
Will try find time or pr..

**Comment by myoung-CS** [comment]
How do I vote on this? Would love this feature! :+1:

**Comment by vitalets** [comment]
@myoung-CS this comment is enough 😉
