### ISSUE TITLE
styles can be updated when the screen changes orientation?

### ISSUE THREAD

**Issue by danielCrespo01** [vitalets/react-native-extended-stylesheet#27]
In my view I have a main view with this I have no problems, but their children are calculated by percentages and I take the dimensions of the previous screen there any solution to this bug.

**Comment by vitalets** [comment]
hi @danielCrespo01 

this is mainly related to #9 
Could you describe how you catch orientation change?

**Comment by vitalets** [comment]
close as dublicate of #9
