### ISSUE TITLE
Global styles

### ISSUE THREAD

**Issue by Randyanto** [vitalets/react-native-extended-stylesheet#28]
I have tried something like this but I got an error. I think this is needed. Thanks.
```
EStyleSheet.build (
  container: {
    flex: 1,
    backgroundColor:'white'
  }
)

const styles = EStyleSheet.create({
  container: '$container'
})
```

**Comment by vitalets** [comment]
@Randyanto I've got your point.
Maybe better just give access to global styles and keep `$variable` for variables only?

**Comment by Randyanto** [comment]
@vitalets yeah I had found a workaround by using `package.json`
[absolute-paths-in-react-native](https://medium.com/@davidjwoody/how-to-use-absolute-paths-in-react-native-6b06ae3f65d1#.giancn7nc)
