### ISSUE TITLE
react-native-extended-stylesheet not working with Rect native 40

### ISSUE THREAD

**Issue by tiempham** [vitalets/react-native-extended-stylesheet#29]
Hi all.
I have used react-native-extended-stylesheet with rn 40 but when I create stylesheet it not working. Style object react-native-extended-stylesheet no Properties when i console it. Thank all.

**Comment by vitalets** [comment]
hi @tiempham are there any errors / warnings ?

**Comment by drdeath113** [comment]
Hi @vitalets no error, warnings. But when I console.log('styles') as examples 
`const styles = EStyleSheet.create({
  column: {
    width: '80%'         // 80% of screen width
  },
  text: {
    color: '$textColor', // use variable $textColor
    fontSize: '1.5rem'   // use relative unit - CSS3 rem
  }
});`
Object js empty.

**Comment by Jiasm** [comment]
Oh, I got the same question, no error, no warnings, and no work:)

**Comment by vitalets** [comment]
- updated npm dependencies
- release 0.3.1
- created empty RN project
- run App from examples

works for me on both ios and android.

@tiempham , @drdeath113 , @Jiasm 
could you kindly recheck with 0.3.1 and fresh RN project?

It seems to be something with upgrading to RN 40..

My dependencies generated from `react-native init`:
```
	"dependencies": {
		"react": "15.4.2",
		"react-native": "0.40.0"
	},
	"devDependencies": {
		"babel-jest": "18.0.0",
		"babel-preset-react-native": "1.9.1",
		"jest": "18.1.0",
		"react-test-renderer": "15.4.2"
	},
	"jest": {
		"preset": "react-native"
	}
```

**Comment by tiempham** [comment]
Thank you for your quick response @vitalets, It working. Have a good day.

**Comment by vitalets** [comment]
You are welcome! 👍
