### ISSUE TITLE
[suggestion]Do we need different style for iOS and android version?

### ISSUE THREAD

**Issue by HaveF** [vitalets/react-native-extended-stylesheet#30]
Thanks for this repo! Help me a lot.

I just read a post which introduce a interesting idea([chinese post](https://noootown.gitbooks.io/deeperience-react-native-boilerplate/content/Infrastructure/React%20Native%20Style.html)), I do not know it is worth to embedded here or not, I just post the code here.

Because iOS and android display different in same style. So they wrap things like this:

```js
import { StyleSheet as RNStyleSheet, Platform } from 'react-native'

class StyleSheet {
  static create(styles: Object): {[name: string]: number} {
    const platformStyles = {}
    Object.keys(styles).forEach((name) => {
      const { ios, android, ...style } = { ...styles[name] }
      let outputStyle = style
      if (ios && Platform.OS === 'ios') outputStyle = { ...style, ...ios }
      if (android && Platform.OS === 'android') outputStyle = { ...style, ...android }
      platformStyles[name] = outputStyle
    })
    return RNStyleSheet.create(platformStyles)
  }
}

export default StyleSheet
```

Then we can use style like this:

```js
export default StyleSheet.create({
  container: {
    flex: 1,
    paddingLeft: 20,
    paddingRight: 20,
    ios: {
      paddingTop: 15,
      paddingBottom: 15,
    },
    android: {
      paddingTop: 10,
      paddingBottom: 10,
    },
    backgroundColor: 'white',
  },
)}
```

Interesting?

**Comment by vitalets** [comment]
hi @HaveF 

it is already possible via [media-queries feature](https://github.com/vitalets/react-native-extended-stylesheet#media-queries)

**Comment by HaveF** [comment]
Wow, sorry, I did notice that! 
Thank!
