### ISSUE TITLE
EStyleSheet.value

### ISSUE THREAD

**Issue by SerzN1** [vitalets/react-native-extended-stylesheet#31]
My case
```
EStyleSheet.value('2.3rem')
```
returns value for default rem value but I had set other build option

EStyleSheet.build({rem: 20});

**Comment by vitalets** [comment]
hi, could you show full code?
Maybe you call `EStyleSheet.value('2.3rem')` before build?

**Comment by vitalets** [comment]
Just re-checked example - it seems to work fine: 
https://github.com/vitalets/react-native-extended-stylesheet/tree/master/examples/rem

Please feel free to reopen if problem still exists.
