### ISSUE TITLE
Percentage is now available by default

### ISSUE THREAD

**Issue by ptomasroos** [vitalets/react-native-extended-stylesheet#32]
Lets move the logic in order to speed up parsing
https://github.com/facebook/react-native/commit/3f49e743bea730907066677c7cbfbb1260677d11

**Comment by vitalets** [comment]
@ptomasroos thanks for sharing.
I think we should wait for RN 43 to get released and when make major release to let people keep using lib on earlier versions of RN.

**Comment by X-Tender** [comment]
Could it be currently used with the underscore syntax? Or are the values there precalculated too?

**Comment by vitalets** [comment]
@X-Tender could you show a demo what you mean?

**Comment by X-Tender** [comment]
Sorry I misunderstood the underscore elements. 😢

Vitaliy Potapov <notifications@github.com> schrieb am Fr., 7. Apr. 2017,
15:00:

**Comment by vitalets** [comment]
Never mind :)

**Comment by joemckie** [comment]
@vitalets it's worth noting that that commit is tagged `0.44`, not `0.43` :smile:

**Comment by vitalets** [comment]
hi @joemckie thanks for info! 
I seems RN team moved this feature from 43 to 44.

**Comment by X-Tender** [comment]
Mmmh no? real percent values are available in RN 0.43. Or waht do you mean? :)

I fooled a bit around and changed
```
tryCalcPercent(str) {
  if (percent.isPercent(str)) {
    return percent.calc(str, this.prop);
  }
  return null;
}
``` 
to:
```
tryCalcPercent(str) {
  if (percent.isPercent(str)) {
    return str;
  }
  return null;
}
``` 
in `value.js` and it worked out of the box. The question is just, change the % behavior there and make it maybe a breaking change or combine it with some kind of additional property.

**Comment by cyrusbowman** [comment]
+1 waiting for this.

**Comment by vitalets** [comment]
Will try to find time for that on the nearest weekend.
Btw, @X-Tender, is everything goes ok with your workaround?
