### ISSUE TITLE
EStyleSheet doesn't change view styles on Android apps

### ISSUE THREAD

**Issue by lightboys22** [vitalets/react-native-extended-stylesheet#35]
EStyleSheet doesn't change view styles on Android apps.  (It works for iOS apps).

Below is an example...
`
<Text style={styles.header}>Hello</Text>
`
`
const styles = EStyleSheet.create({
  header: {
    color: 'red',
  }
});
`

**Comment by vitalets** [comment]
Did you call `EStyleSheet.build()` ?

**Comment by lightboys22** [comment]
Thanks.  Calling EStyleSheet.build() after EStyleSheet.create() works.
