### ISSUE TITLE
Variables don't support division

### ISSUE THREAD

**Issue by joemckie** [vitalets/react-native-extended-stylesheet#37]
Is there currently any way to implement division with a variable? Take the following example which creates a label with rounded sides:

```js
const styles = EStyleSheet.create({
  label: {
    $height: 30,
    borderRadius: '$height / 2',
    height: '$height',
  }
});
```

This is throwing an error that says `$height / 2` is an unresolved variable. The docs also suggest that division isn't implemented.

Is there a reason for that or is it just unimplemented? I could take a look into it if there's nothing blocking it.

**Comment by vitalets** [comment]
hi @joemckie 

It seems redundant because we can replace division with multiply:
```js
const styles = EStyleSheet.create({
  label: {
    $height: 30,
    borderRadius: '$height * 0.5',
    height: '$height',
  }
});
```

**Comment by joemckie** [comment]
Hmm... true. It is a little confusing that it initially appears to be
broken though. If it won't be implemented perhaps it needs to be made
clearer in the docs?

**Comment by vitalets** [comment]
Agree. Now will add to docs.
Also just looked on code, it seems rather cheap to support division. I think it's better as nobody read docs :)

**Comment by joemckie** [comment]
Yeah I agree, it seems weird to not implement it, even if it does just
coerce `/ 2` to `* 0.5` behind the scenes. :)
