### ISSUE TITLE
Support for complex operations

### ISSUE THREAD

**Issue by joemckie** [vitalets/react-native-extended-stylesheet#39]
I saw the commit at [#633058c](https://github.com/vitalets/react-native-extended-stylesheet/commit/a9b9a1c841b1bd8f80600a79593c1b5b7533bea8) and thought complex operations would be a really handy feature actually. What do you think?

**Comment by vitalets** [comment]
I agree it can be useful.
But also not trivial to implement.
We can have a look on libs mentioned in [this SO question].(http://stackoverflow.com/questions/2276021/evaluating-a-string-as-a-mathematical-expression-in-javascript)

Another thought is to use value as a function for that.
This already works:
```js
{
  lineHeight: () => EStyleSheet.value('$x') * EStyleSheet.value('$y') + 1,
}
```

Maybe just make it less verbose:
```js
import EStyleSheet, {val} from 'react-native-extended-stylesheet';
{
  lineHeight: () => val('$x') * val('$y') + 1,
}
```

**Comment by joemckie** [comment]
Hmm that works but IMO it's not the most elegant solution, it'd be nice if it worked inline. The way I envisioned it working was to create an array of operations from the string and to reduce it to a single value.

Pseudo-code, but something like this:

```js
// StyleSheet code
{
  height: '$height + $height2 - 20'
}

// Turns to:
[
  {operator: '+', v1: '$height', v2: '$height2'}
  {operator: '-', v1: 'result from above', v2: '20'}
].reduce(acc, op) => {
  acc = exec(op);
  return acc;
}, 0);
```

The problem I can see with trying to do it this way would be applying the correct order of BODMAS...

**Comment by vitalets** [comment]
Finally [value as a function](https://github.com/vitalets/react-native-extended-stylesheet#value-as-a-function) should be sufficient enough for complex operations.
