### ISSUE TITLE
Problem with create

### ISSUE THREAD

**Issue by sylvainbaronnet** [vitalets/react-native-extended-stylesheet#4]
Hi,

I tried to use this module without success, I always got an empty object as a result, even with the simple example on the readme.
I looked at the code and I was able to make it work by changing (in api.js) : `if (this.builded)` to `if (!this.builded)` since in my test `this.builded` was always false and it looks like it needs to go through `sheet.calc()`

Maybe i'm missing something...

**Comment by vitalets** [comment]
hi @sylvainbaronnet 
do you call `EStyleSheet.build()` in entry script?

**Comment by sylvainbaronnet** [comment]
Sorry it was late^^ No I didn't, I though it was only if there's vars to "build", it works correctly.

Maybe your should switch it to step 1 in doc

**Comment by vitalets** [comment]
ok, will update docs.
Thanks for feedback!
