### ISSUE TITLE
Nested global variables

### ISSUE THREAD

**Issue by lucasff** [vitalets/react-native-extended-stylesheet#41]
```
EStyleSheet.build({
    dashboard: {
         $valueFontSize: 26 * fontScale,
    }
});
```

Currently, this is not possible because the check is against the first letter (`charAt(0)`).
Say I want to use:

```
EStyleSheet.create({
    text: {
         fontSize: '16 * dashboard.$valueFontSize',
    }
});

```
Could we have this support?

**Comment by vitalets** [comment]
hi @lucasff !
Could you show the full example what do you expect?
Thanks!

**Comment by lucasff** [comment]
@vitalets I updated my comment.
Thanks!

**Comment by vitalets** [comment]
Hi @lucasff 

`$` should be used only in top level variable name, nested sub-variables can be without it.

Working example:
```js
EStyleSheet.build({
    $dashboard: {
         valueFontSize: 26
    }
});
```
Usage in the component:
```js
const styles = EStyleSheet.create({
    text: {
         fontSize: '16 * $dashboard.valueFontSize'
    }
});
```
Hope that helps.
Sorry for late response.
