### ISSUE TITLE
EStyleSheet.memoize does not work for Object params

### ISSUE THREAD

**Issue by JulioC** [vitalets/react-native-extended-stylesheet#45]
If you pass objects to a memoized function, it considers that the value is the same, due to use of `Object.toString` (indirectly called, when it uses `Array.join`) when creating the cache key. 

Code to reproduce the error:

```js
import EStyleSheet from 'react-native-extended-stylesheet';

const memoized = EStyleSheet.memoize((data) => console.log(data));

// These two work as expected:
memoized({id: 1}); // should log
memoized({id: 1}); // should not log

// This one won't
memoized({id: 2}); // should log
```

See [src/memoize.js#L7](https://github.com/vitalets/react-native-extended-stylesheet/blob/master/src/memoize.js#L7)

**Comment by vitalets** [comment]
Hi @JulioC 

I've checked [lodash.memoize](https://lodash.com/docs/4.17.4#memoize)- it works the same way.
The solution for object params is described here: https://github.com/caolan/async/issues/96

I think I will deprecate `EStyleSheet.memoize` in favor of `lodash.memoize` that can accept custom hash function to deal with objects. also it can be installed as [separate package](https://www.npmjs.com/package/lodash.memoize).

**Comment by JulioC** [comment]
Lodash uses a reference for the args as a cache key. In fact I was using it as a workaround on my code.

I believe deprecating it is a nice move, since it's beyond the scope of stylesheets!

By the way, the code in the first post was wrong, the correct is to use the same object:

```js
import EStyleSheet from 'react-native-extended-stylesheet';

const memoized = EStyleSheet.memoize((data) => console.log(data));

const obj1 = {id: 1};
const obj2 = {id: 2};

// These two work as expected:
memoized(obj1); // should log
memoized(obj1); // should not log

// This one won't
memoized(obj2); // should log
```

**Comment by vitalets** [comment]
Removed in 0.6.0. Thank you! 👍

**Comment by Vlad-Zhukov** [comment]
Have a look at [moize](https://github.com/planttheidea/moize), it's fast and supports serialization of arguments.
