### ISSUE TITLE
CSS psudo class or psudo elements selectors like after and before in react native

### ISSUE THREAD

**Issue by aniruddhashevle** [vitalets/react-native-extended-stylesheet#46]
Is it feasible to use css psudo class or psudo elements selectors like after, before, etc in react native? Or any other way around out there?

Or could we do something to make it feasible in this amazing package?

**Comment by vitalets** [comment]
hey @aniruddhashevle ! 
Currently `after / before` pseudo classes are not supported as I did not get the requests for that.
Could you describe the problem that you want to solve?

**Comment by vitalets** [comment]
close as outdated.
