### ISSUE TITLE
warning : There appears to be trouble with your network connection. Retrying...

### ISSUE THREAD

**Issue by syedirfan7** [vitalets/react-native-extended-stylesheet#48]
I am trying to install the examples folder i get the below issue 
using : react-native init ExtendedStyleSheetExample

![error](https://user-images.githubusercontent.com/6966314/29274319-1088dbec-8125-11e7-9873-7e421e2c8f6c.png)

**Comment by vitalets** [comment]
hi @syedirfan7 It seems to be issue with your network connection.  
`ExtendedStyleSheetExample` is just a directory name.

Please, close the issue if everything ok now.

**Comment by syedirfan7** [comment]
yes it was because of network !! solved it and worked as expected.. thank you !!
