### ISSUE TITLE
Implement CSS `mediaQueries`

### ISSUE THREAD

**Issue by grabbou** [vitalets/react-native-extended-stylesheet#5]
Hey,

Cool module! I had similar idea a while ago and created that gist to demo how my internal implementation works -> https://gist.github.com/grabbou/72767db51f97fe86cfea

I don't think there's a need for yet another stylesheet package, so I was thinking we could add that in here.

Happy to merge that in, let me know what you think.

**Comment by vitalets** [comment]
hey, great idea!
I think we should merge it definetely.

**Comment by tlvenn** [comment]
+1 @grabbou where is the PR ;)

**Comment by grabbou** [comment]
Ah, still got no time for that! I think I'll just open my internal version and maybe one of you guys will try porting it here (or stick with it if you prefer lighter impl.)

**Comment by tlvenn** [comment]
Would be great, let us know when it's ready, thanks !

**Comment by vitalets** [comment]
thanks! I will try to find time for porting.

**Comment by tlvenn** [comment]
@vitalets awesome 👍

**Comment by vitalets** [comment]
@grabbou @tlvenn 
hi guys 
pls check when you have time with 0.2.0.
thx!
