### ISSUE TITLE
Outline for debugging not working?

### ISSUE THREAD

**Issue by AnthonyLamot** [vitalets/react-native-extended-stylesheet#51]
From: https://github.com/vitalets/react-native-extended-stylesheet#outline-for-debug

I just gave it a try but didn't manage to get it working. Any ideas?

```
import EStyleSheet from 'react-native-extended-stylesheet';
EStyleSheet.build({ $outline: 1 });
```

In my `app/index.js`

**Comment by vitalets** [comment]
Will re-check! thank you!

**Comment by vitalets** [comment]
I tried with [example for readme screenshot](https://github.com/vitalets/react-native-extended-stylesheet/blob/master/examples/readme) - everything works for me:
```js
// app.js
EStyleSheet.build({
  $textColor: 'black',
  $buttonColor: '#679267',
  $outline: 1, // outline!
  $rem: 18,
});
```
![image](https://user-images.githubusercontent.com/1473072/31024772-d0003776-a548-11e7-9a54-fbf62e224152.png)

Could you re-check and reopen with your code if problem still exists.
Thanks!

**Comment by AnthonyLamot** [comment]
Hi @vitalets, sorry for not getting back sooner. Unfortunately I don't get it to work yet.

From my `index.js`:

```
import Meteor from 'react-native-meteor';
import React from 'react';
import EStyleSheet from 'react-native-extended-stylesheet';

import settings from './config/settings';
import { AlertProvider } from './components/Alert';
import RootStack from './config/routes';

Meteor.connect(settings.SERVER_URL);

EStyleSheet.build({ $outline: 1 }); // not working?

const App = () => (
  <AlertProvider>
    <RootStack />
  </AlertProvider>
);

export default App;
```

This file is located in an `App` folder. There are separate index.js files to initiate on Android or iOS, but I don't think that should be a problem?

I am using `react-native run-android` on a connected device, but I think that is fine too?

**Comment by AnthonyLamot** [comment]
@vitalets that actually makes a lot of sense. I simply had not considered it. Thank you for clarifying and your help! (As well as updating the doc.)
