### ISSUE TITLE
Question: When to use underscored styles ❓

### ISSUE THREAD

**Issue by deadcoder0904** [vitalets/react-native-extended-stylesheet#57]
I have read the docs about `underscored styles` but don't know what to use & why ❓ 

Currently, I'm using `styles._text` styles everywhere bcz once `styles.text` was not working. 

So @vitalets  if u can explain when to use `underscored styles`❓

**Comment by vitalets** [comment]
hi @deadcoder0904 !
Underscored styles are intended for components with explicit styling attributes. For example, `<Icon color="red">`. If you already defined styles for text:
```js
const styles = EStyleSheet.create({
  text: {
    color: 'red'
  }
});
```
 and want icon color to be the same, you can reuse text's style:
```js
<Icon color={styles._text.color}>
```

**Comment by deadcoder0904** [comment]
Cool got it thanks 🎉
