### ISSUE TITLE
App Crashes When Percentage is used [Expo]

### ISSUE THREAD

**Issue by kenshinman** [vitalets/react-native-extended-stylesheet#58]
Hi, thanks for this package.
I just  that my app crashes whenever i declare a percentage value. Example code below.

```
 import EStyleSheet from "react-native-extended-stylesheet";

const styles = EStyleSheet.create({
  root: {
    flex: 1
  },
  meetupCard: {
    height: 200,
    width: 175,
    marginLeft: '1.5%',
        backgroundColor: "#f56d79"
      }
    });

    export default styles;
```

When ever I comment out the percentage line, Everything works find.
### Edit

Seems this only happens when I use it on any `margin` value
Is this a bug? Thakns

**Comment by vitalets** [comment]
Hi @kenshinman !

could you show a screenshot with error?
I've tested with that snack https://snack.expo.io/ryjR31tpZ - it works for me.

**Comment by vitalets** [comment]
Re-checked again - everything works.
Feel free to re-open if the problem still exists.
