### ISSUE TITLE
Common styles ?

### ISSUE THREAD

**Issue by deadcoder0904** [vitalets/react-native-extended-stylesheet#59]
Is there any way to create Common styles since I'm repeating a lot of code.

Currently, my approach is 

```js
<View style={[styles.commonStyle, styles.A]} />
<View style={[styles.commonStyle, styles.B]} />
```

But, I think the following approach would be much better

```js
EStylesheet.create({
	$commonStyles: {
		margin: 10,
		padding: 10,
	},
	A: {
		...$commonStyles,
		color: 'red',
	},
	B: {
		...$commonStyles,
		color: 'green',
	},
})
```

So that in my component I will only do this -

```js
<View style={styles.A} />
<View style={styles.B} />
```

Someway the Component would be much more readable. What do u think @vitalets ❔

**Comment by vitalets** [comment]
hi @deadcoder0904 !

I got you idea. Maybe like this:
```js
const commonStyles = {
    margin: 10,
    padding: 10,
};
const styles = EStylesheet.create({
    A: {
        ...commonStyles,
	color: 'red',
    },
    B: {
	...commonStyles,
	color: 'green',
    },
});
```

**Comment by deadcoder0904** [comment]
Yaa I thought about that too, but then I might create a lot of objects

**Comment by vitalets** [comment]
From the performance perspective creating many little sheets that just serve as commons looks not good - as each real sheet causes style creation on native side that anyway takes some resources. I think storing common parts in helper objects is ok: you don't create unneeded sheets and can always group them to have more clean code:
```js
const commonStyles = {
    button: {
        margin: 10,
        padding: 10,
    },
    link: {
        color: 'blue'
    }
};
const styles = EStylesheet.create({
    A: {
        ...commonStyles.button,
	color: 'red',
    },
    B: {
	...commonStyles.button,
	color: 'green',
    },
});
```

**Comment by deadcoder0904** [comment]
Cool enough 👍

**Comment by anisimov74** [comment]
@vitalets thanks for the library! It's really helpful. 
Regarding this common style. I see no way to create common styles that use color variables.
An example:
```
export const commonStyle = {
 height: 1,
 backgroundColor: '$background'
}
```
