### ISSUE TITLE
Multiple math operators

### ISSUE THREAD

**Issue by deadcoder0904** [vitalets/react-native-extended-stylesheet#60]
Currently only 1 operator is supported, so if I have to do the following I can't 

```js
{
  height: '$deviceHeight/2-100'
}
```

Instead I have to do

```js
{
  $halfDeviceHeight: '$deviceHeight/2',
  height: '$halfDeviceHeight-100'
}
```

So for many operators this becomes unnecessary & this happens for quite a few use cases that I've encountered in the past few weeks or so

**Comment by vitalets** [comment]
Yes, it seems to be rare cases.
Multiple operators support is not trivial - we should consider operators priority and maybe support brackets - all this increases complexity. 
I'm thinking about setting such values [via function](https://github.com/vitalets/react-native-extended-stylesheet#value-as-a-function). Something like this:
```js
{
  height: () => EStyleSheet.value('$deviceHeight/2') - 100
}
```
Currently this will work only with *global* variables.
But technically it is possible to provide local variables to calls of `EStyleSheet.value()` during calculation of particular sheet.

**Comment by deadcoder0904** [comment]
When complex UI comes, its not a rare case. As I am developing many RN apps right now, I feel that need because for different devices, the UI doesn't seem to work. `react-native-extended-stylesheet` reduces lot of my work & this particular case is what makes me to create unnecessary local variables. Thank you for this repo. It really helps a lot 😄

**Comment by vitalets** [comment]
ok, thanks for the feedback!
Will such approach be sufficient for you tasks?
```js
{
  height: () => EStyleSheet.value('$deviceHeight/2') - 100
}
```

**Comment by deadcoder0904** [comment]
Yep that works perfectly fine

**Comment by vitalets** [comment]
Ok. I will have a look.
