### ISSUE TITLE
Invalid prop 'width'  of type 'string', Expected 'number'

### ISSUE THREAD

**Issue by harwinvoid** [vitalets/react-native-extended-stylesheet#64]
```
import EStyleSheet from 'react-native-extended-stylesheet';

export default EStyleSheet.create({
  container: {
    fontSize: '2rem',
    width: '10%',
  },
});
```
![img_0911](https://user-images.githubusercontent.com/12931494/32363426-4cfb103e-c03d-11e7-9080-804fcd522b89.PNG)

RN version 0.30
ios 11

**Comment by vitalets** [comment]
Hi! It's because of RN version that does not support percents natively. I will think what we can do.
By the way, could you share the reasons why you don't update RN?

Related: https://github.com/vitalets/react-native-extended-stylesheet/issues/32

**Comment by harwinvoid** [comment]
it a long story

**Comment by harwinvoid** [comment]
thank a lot。 the reason is a long story

**Comment by vitalets** [comment]
Anyway, the workaround can be done by value as a function:
```js
export default EStyleSheet.create({
  container: {
    fontSize: '2rem',
    width: () => 0.1 * Dimensions.get('window').width
  },
});
```

Feel free to reopen if needed.
