### ISSUE TITLE
Support shorthands

### ISSUE THREAD

**Issue by Krizzu** [vitalets/react-native-extended-stylesheet#69]
Hey!

Thanks for this cool tool. I was wondering if you'd like to support css shorthands (like, `padding: 5 10 5 8`), which consequently changes that to `paddingTop: 5, paddingRight: 10, paddingBottom: 5, paddingRight: 8`.

I'd happy to help with that.

**Comment by vitalets** [comment]
Hey @Krizzu !
I think it makes sense.
There are some more cases that should be considered:
1. Variables:
```js
padding: '$a 1 2 3'
```
2. Calculations:
```js
padding: '$a + 10 1 2 3'
```
I think we should deny calculations in shorthand props as it is impossible to parse normally.

So, you are welcome to take leadership on this 👍 
Also the following project could help: https://github.com/styled-components/css-to-react-native

**Comment by Krizzu** [comment]
Great!

I'll dive in on the weekend

**Comment by Krizzu** [comment]
Hey @vitalets 👋 
Need suggestion here: using `css-to-react-native` requires styles to have `px` unit to be parsed. How should I proceed with that fact? Append units to values or allow them to be passed in shorthands?

Thanks 👍

**Comment by vitalets** [comment]
> Need suggestion here: using css-to-react-native requires styles to have px unit to be parsed. I'm going to add units, for the sake of getting the outcome. Or maybe you can think of a different way?

Could you add some tests to see how adding `px` will work with different cases? 
Will not it break variables and percents? 
1. `padding: '$a 1 2 3'`
2. `padding: '10% 1 2 3'` 

> Also, my suggestion here is to limit of supported shorthands to few: `margin`, `padding`, `borderRadius`, `borderWidth`, `shadowOffset`.

Why can not we support all?

**Comment by Krizzu** [comment]
>Could you add some tests to see how adding px will work with different cases?
Will not it break variables and percents?

Yeah, I still have to add functionality for it, will add test to prove it's working.

>Why can not we support all?
Some of them are `background` which just evals to `backgroundColor`, or `borderWidth`, which already defines all borders in RN.

Here's a list that I believe is supported by `css-to-react-native`, we can choose which make sense and add them

https://github.com/styled-components/css-to-react-native/blob/master/src/transforms/index.js#L54-L71

**Comment by gurs1kh** [comment]
> ```
> 
> 1. Calculations:
> 
> ```js
> padding: '$a + 10 1 2 3'
> ```
> 
> I think we should deny calculations in shorthand props as it is impossible to parse normally.

One way to get around this is to allow for arrays to be used.
ie:
```js
padding: ['$a + 10', 1, 2, 3]
```

This also is a good stylistic alternative to using a space-separated string

**Comment by vitalets** [comment]
> One way to get around this is to allow for arrays to be used.

Agree. Looks nice! 👍

**Comment by hustcer** [comment]
+1

**Comment by vitalets** [comment]
So finally I think there will be more problems than profit from that feature.
