### ISSUE TITLE
How to use global value in third party component properties?

### ISSUE THREAD

**Issue by vikrantnegi** [vitalets/react-native-extended-stylesheet#71]
I'm using a third party component librabry called `react-native-elements` it has various prebuild react native components like checkboxes, buttons etc.

I'm using one checkbox component and it has prop `checkedColor` which is used to basically define color of the checkmark icon when the checkbox is checked.

Now I want to use my global variable `$primaryColor` to used as a value in the prop like this.

```js
<CheckBox
  checked={checkName}
  onPress={() => this.setState({ checkName: !checkName })}
  component={TouchableWithoutFeedback}
  checkedColor={styles.$primaryColor}
/>
```
This will not work as global variables are not available like this.

For the above code to work I'll need to define the primary color in the local scope like below.

```js
const styles = EStyleSheet.create({
  $primaryColor: "#f06", 
});
```
But Now I'm not using global variables and will need to change the variable value two times if I've to change the color value in the future. 

Any Idea on how can is reuse global variables for the above case?

Let me know if it's not clear on what I'm trying to ask and thanks for this awesome library.

**Comment by vitalets** [comment]
I think `checkedColor={EStyleSheet.value('$primaryColor')}` should do the job.

**Comment by vikrantnegi** [comment]
Wow, that works and it's so simple. 
Though I believe this deserves a mention in the documentation.
Thoughts?

**Comment by vitalets** [comment]
@vikrantnegi the similar way:
```js
<View style={{
  backgroundColor: EStyleSheet.value('$primaryColor')
}}>
...
</View>
```

**Comment by vikrantnegi** [comment]
Thanks.

**Comment by vitalets** [comment]
Agree! I would appreciate if you add this as PR =)
