### ISSUE TITLE
Is possible to use it with size-matters?

### ISSUE THREAD

**Issue by obetomuniz** [vitalets/react-native-extended-stylesheet#79]
The scaling feature is based on a scale function that uses absolute dimensions values of an element to resize. 

I want to use relative dimensions based on device dimensions to keep the aspect of my app with a complex layout in more than one device screen. Can I use some way to customize it and/or abstract some third-party library or custom function with the extended-stylesheet library? Like this [library](https://github.com/nirsky/react-native-size-matters).

The `.value()` seems an interesting way to extend the extended-stylesheet library, but it is very verbose in my case (I'll need to use it in every `width`, `height`, `padding`, `margin`,  `fontSize`, etc). The react-native-size-matters library includes 3 units: `@s`, `@vs` and `@dm` and it is very useful to make the maintainability clean. 

Is possible use this same approach with this library?

**Comment by vitalets** [comment]
@obetomuniz 
1. Could you show a short snippet how you solution looks with .value()?  
2. Is not it possible to set `$scale` value based on device dimensions? Something like this:
```js
const scale = deviceWidth < 300 ? 1 : 1.5;
const styles = EStyleSheet.create({
  $scale: scale,
  button: {
    width: 100,
    height: 20,
    marginLeft: 10
  }
});

```

**Comment by obetomuniz** [comment]
Hey @vitalets, thank you for the feedback :D 

Using the size-matters formula that provide for use `scale`, `verticalScale` and `moderateScale `, the `.value()` will be something like this: 
```
const styles = EStyleSheet.create({
  button: {
    width: () => 100 * EStyleSheet.value('$scale'),
    height: () => 20 * EStyleSheet.value('$verticalScale'),
    marginLeft: () => 10 *  EStyleSheet.value('$scale')
  }
});
```

As you can see, it will be verbose and hard to maintain a huge application. Is there some way to create global functions or mixins?

**Comment by obetomuniz** [comment]
FYI: I want to avoid static responsive values like `const scale = deviceWidth < 300 ? 1 : 1.5;` once we have a bunch of screen dimensions (width/height) to support.

**Comment by obetomuniz** [comment]
Doing some research and thinking out of the box 😂 ... Is possible to create something like this:

```
EStyleSheet.build({ // always call EStyleSheet.build() even if you don't use global variables!
  $s: calcs to return the scale vlaue,
  $vs: calcs to return the verticalScale vlaue,
});

const styles = EStyleSheet.create({
  button: {
    width: '100 * $s',
    height: '20 * $vs',
    marginLeft: '10 * $s'
  }
});
```

Is there some way or suggestion to remove the `*` operator and use just `number$formula`? Like this:

```
const styles = EStyleSheet.create({
  button: {
    width: '100$s',
    height: '20$vs',
    marginLeft: '10$s'
  }
});
```

**Comment by vitalets** [comment]
I think ideally we should not have `100@s / 100$s / 100 * $s` for scaling. Just `100`.
Currently EStyleSheet supports single scaling factor for all directions. 
And these two examples are equivalent:
1.
```js
EStyleSheet.build({
  $s: 1.5,
});
const styles = EStyleSheet.create({
  button: {
    width: '100 * $s',
    marginLeft: '10 * $s'
  }
});
```
2.
```js
EStyleSheet.build({
  $scale: 1.5,
});
const styles = EStyleSheet.create({
  button: {
    width: 100, // automatically turns into 150
    marginLeft: 10 // automatically turns into 15
  }
});
```
But the second looks more clean to me.
As I understand the problem - you need separate scaling factor for **vertical** and **horizontal** directions. Yes?

For me it sounds reasonable. The solution can be to support direction specific scaling:
```js
EStyleSheet.build({
  $scaleHorizontal: 1.5,
  $scaleVertical: 2,
});

const styles = EStyleSheet.create({
  button: {
    width: 100, // automatically turns into 150
    height: 20, // automatically turns into 40
    marginLeft: 10 // automatically turns into 15
  }
});
```
Will it solve the issue?

**Comment by obetomuniz** [comment]
Wow! I'll consider this solution. My concern is that it is not based in a specific dimension of device to use as reference as you can see [here](https://github.com/nirsky/react-native-size-matters/blob/master/lib/scalingUtils.js#L4).
