### ISSUE TITLE
letterSpacing will work or not ?

### ISSUE THREAD

**Issue by navinprasadk** [vitalets/react-native-extended-stylesheet#80]

**Comment by vitalets** [comment]
@navinprasadk Could you show the code?

**Comment by navinprasadk** [comment]
`import { Dimensions } from 'react-native';
import EStyleSheet from 'react-native-extended-stylesheet';

const imageWidth = Dimensions.get('window').width / 2;
export default EStyleSheet.create({
  container: {
    alignItems: 'center',
  },
  containerImage: {
    alignItems: 'center',
    justifyContent: 'center',
    width: imageWidth,
    height: imageWidth,
  },
  image: {
    width: imageWidth / 2,
  },
  text: {
    fontWeight: '600',
    fontSize: 20,
    marginTop: 20,
    color: '$white',
    letterSpacing:'2',
  },
});
`
This is the code @vitalets

**Comment by vitalets** [comment]
@navinprasadk 
According to RN docs [letterSpacing](https://facebook.github.io/react-native/docs/text.html#style) is supported only for iOS.
For Android I found this package: [react-native-letter-spacing](https://www.npmjs.com/package/react-native-letter-spacing)
