### ISSUE TITLE
Extended styles sheets not working with React native version 0.53.3

### ISSUE THREAD

**Issue by shubhi15** [vitalets/react-native-extended-stylesheet#82]
Hello

I am trying to use EStyleSheet.create method to create my styles but it is returning me empty object.
Code refrence
import EStyleSheet from 'react-native-extended-stylesheet';

const styles = EStyleSheet.create({
  background: {
    backgroundColor: '#fff',
    flex: 1,
  },
});
console.log("exported category styles");
console.log(styles)
export default styles;

my console statement returning styles as empty object.

Regards
Shubhi

**Comment by vitalets** [comment]
Hi @shubhi15!

Do you call `EStyleSheet.build()` in your code?

**Comment by anderllr** [comment]
I'm with the same error, and I called EStyleSheet.build() in my App.js file.

**Comment by vitalets** [comment]
I think this is because styles are imported (and executed) before `EStyleSheet.build()` call.
Imagine you have `app.js`:
```js
import styles from './styles'; // <-- occurs before EStyleSheet.build()

EStyleSheet.build();
```

and `styles.js` is:
```js
import EStyleSheet from 'react-native-extended-stylesheet';

const styles = EStyleSheet.create({
  background: {
    backgroundColor: '#fff',
    flex: 1,
  },
});
console.log("exported category styles");
console.log(styles); // <-- here styles are not builded yet and console shows {}
export default styles; 
```


If this does not help, please show your code as Expo snack using this template: https://snack.expo.io/@vitalets/extended-stylesheet-simple

**Comment by anderllr** [comment]
Thanks @vitalets you're right, I've forgotten to call the js file where EStyleSheet.build(); was configured.

**Comment by vitalets** [comment]
You are welcome!
