### ISSUE TITLE
Themes not getting updated at runtime

### ISSUE THREAD

**Issue by shubhi15** [vitalets/react-native-extended-stylesheet#83]
Hello 
I have tried example
 https://github.com/vitalets/react-native-extended-stylesheet/tree/master/examples/theming

But it is only updating variables if styles are specified as inline styles. within component
If styles within component is referenced from outside files then styles are not getting updated even after re-rendering of component.

Regards
shubhi

**Comment by vitalets** [comment]
hi @shubhi15 !

could you show how you changed the example so it stopped to work?

**Comment by shubhi15** [comment]
I am using it in similar way as described in example but it is not working with referenced styles but works well with inline styles

**Comment by vitalets** [comment]
Please, show the code.

**Comment by shubhi15** [comment]
Hello PFB code i am using for dynamically updating themes:
In this inline style text box color is updated if i click ob change theme but ouside style text box color not getting updated.

import lightTheme from '../commonStyles/light';
import darkTheme from '../commonStyles/dark';

EStyleSheet.build(lightTheme);

class CategoryScreen extends Component {
  
  constructor() {
    super();
    this.state = {
      render: true
    };
  }
  componentWillMount() {
   

  }
  changeTheme(darkTheme, lightTheme) {
    const theme = EStyleSheet.value('$theme') === 'light' ? darkTheme : lightTheme;
    let ss = EStyleSheet.build(theme);
    this.setState({ render: false }, () => this.setState({ render: true }));
  }

  render = () => {
    return (
      <Container>
        <View>
          <Text style={styles.buttonTransparent}>
            outside style
          </Text>
        </View>
        <View>
          <Text style={{
            padding: 12,
            paddingLeft: 17,
            fontSize: 16,
            color: EStyleSheet.value('$primaryTextcolor')
          }}>
            iniline style
          </Text>
          <Text onPress={() => this.changeTheme(darkTheme, lightTheme)}>>
           Change Them
          </Text>
        </View>
        {/* <FlatList
          data={this.props.categoryArr}
          renderItem={({ item }) =>
            <CardComponent cardObject={item} navigateToImageTab={() => this.props.navigateToImageTab(item)} >
            </CardComponent>}
        /> */}
      </Container>
    );

  }
}

**Comment by vitalets** [comment]
Seems you should check `state.render` flag inside `render()` and return null to actually re-render component. Otherwise React caches component tree and does not update styles:
```js
render = () => {
    if (!this.state.render) {
        return null;
    }
    return (
      <Container>
        <View>
    ...
```

Feel free to reopen if it does not help.
I also created expo example for testing themes: https://snack.expo.io/HyujGlKcf

**Comment by shubhi15** [comment]
Nope theme is still not updating.... :(

**Comment by vitalets** [comment]
@shubhi15 Could you modify my [expo example](https://snack.expo.io/HyujGlKcf) with your code to demonstrate it?

**Comment by eayllon1** [comment]
Having the same problem. Styles stay with the dimensions they were loaded into with, even after refreshing the component, when the stylesheet had been made external.

**Comment by vitalets** [comment]
@eayllon1 Could you show a demo code of problem?

**Comment by pgonzalez-santiago** [comment]
Same problem here.

**Comment by guopeng1994** [comment]
so ? any update?

**Comment by vitalets** [comment]
Please provide the details: sample code / expo snack showing the problem. Otherwise it is impossible to help.

**Comment by swizes** [comment]
Changing return of the screen to null is not a solution, it is just a dirty fix. A normal theme change should be smooth not like displaying nothing and re-displaying with changed theme...
