### ISSUE TITLE
EStyleSheet.create - undefined is not an object.

### ISSUE THREAD

**Issue by FantasticSWT** [vitalets/react-native-extended-stylesheet#85]
![image](https://user-images.githubusercontent.com/38369131/38763889-b86fd434-3fd7-11e8-9873-fe29d3e8ff3a.png)
![image](https://user-images.githubusercontent.com/38369131/38763891-cc2a6624-3fd7-11e8-83ea-597b1109f1d5.png)
I tried to look at the library, but I think should be no prob. And I had added build at app entry.

![image](https://user-images.githubusercontent.com/38369131/38763896-ecf5c308-3fd7-11e8-8419-92c116eebb47.png)

Please help.

**Comment by vitalets** [comment]
hi @FantasticSWT ! The problem is in import statement.
There should be:
```js
import EStyleSheet from 'react-native-extended-stylesheet';
```
instead of:
```js
import { EStyleSheet } from 'react-native-extended-stylesheet';
```
