### ISSUE TITLE
Question: Can I uncache, and re-cache just one regular noraml StyleSheet

### ISSUE THREAD

**Issue by Noitidart** [vitalets/react-native-extended-stylesheet#86]
You have a super module here. However I didn't need all of this. I just had one StyleSheet in my entire app, I needed to use a variable in there for a color. I want to uncache it from native, re-build it. May you please show how I can do this?

**Comment by vitalets** [comment]
hi @Noitidart ! 
Could you show the code how you expect it should work?

**Comment by Noitidart** [comment]
Thanks so much for asking and willing to help.


I have code like this:

```
const COLORS = {
     primary: 'red';
}

const styles = StyleSheet.create({
    title: {
       color: COLORS.primary
    }
});


<Text style={styles.title} />
<Button onPress={this.changePrimaryColor} title="Change Primary Color" />

changePrimaryColor() {
     COLORS.primary = 'green';
     COLORS.title.color = COLORS.primary;
     style.recache();
}
```

**Comment by vitalets** [comment]
Closing as the question is answered.
