### ISSUE TITLE
flex: 1 does not work

### ISSUE THREAD

**Issue by UdayKandpal** [vitalets/react-native-extended-stylesheet#93]
Properties like 
   **flex: 1**
   **flexDirection: 'column'**
do not work with EStyleSheets.create() method. They do not render on the View container.

**Comment by vitalets** [comment]
Please create an expo sample reproducing the issue.
Use this [expo template](https://snack.expo.io/@vitalets/extended-stylesheet-simple).

**Comment by MeganGilligan1** [comment]
@UdayKandpal Did you find a fix for this? 

I've changed my Stylesheet.create to EStyleSheet.create and it just seems to break it - as if it's not working with Flex.

![image](https://user-images.githubusercontent.com/25102188/47907382-0b82be80-de83-11e8-8d3f-a196cc2d68f6.png)
